# 使用 Nginx 基础镜像
FROM nginx:1.25.1-alpine

# 复制打包好的文件到 Nginx 默认目录
COPY ITPortal.Web /usr/share/nginx/html/
COPY nginx.conf /etc/nginx/conf.d/default.conf
chmod -R 755 /usr/share/nginx/html

# 暴露 80 端口
EXPOSE 80

# 启动 Nginx
CMD ["nginx", "-g", "daemon off;"]