@Sqllineage_HostAddress = http://localhost:5022

GET {{Sqllineage_HostAddress}}/weatherforecast/
Accept: application/json

###

###
POST {{Sqllineage_HostAddress}}/weatherforecast
Accept application/json

