// Set translateData here
export const TranslateData = Object({
  formValidMsg: 'form.is.not.valid',
  saveSuccess: 'save.success',
  saveFail: 'save.fail',
  fileUploadSuccess: 'upload.success',
  deleteSuccess: 'delete.success',
  fileUploadFail: 'upload.fail',
  deleteFail: 'delete.fail',
  isDelete: 'is.delete',
  confirm: 'confirm',
  yes: 'yes',
  no: 'no',
  input: 'please.input',

  manual: 'label.manual',
  automatic: 'label.automatic',
  dataFetchingFailed: 'info.data.fetching.failed',
  copy: 'operate.copy',
  error: 'info.error',
  noData: 'info.noData',
  tips: 'info.tips',
  success: 'info.success',
  fail: 'info.fail',
  secretLevel1: 'info.public.grade',
  secretLevel2: 'info.internal.use.level',
  secretLevel3: 'info.secret',
  secretLevel4: 'info.restricted.secret',
  secretLevel5: 'info.public.gradRegistered.secret',
  noApplication: 'info.no.application',
  selectDataApplication: 'info.select.data.application',
  psdNameInvalid: 'info.psd.name.invalid',
  development: 'info.under.development',
  MySql: 'label.MySql.database',
  MariaDB: 'label.MariaDB.database',
  PostgreSql: 'label.PostgreSql.database',
  SQLServer: 'label.SQLServer.database',
  otherDatabase: 'label.other.database',
  deleteConfirm: 'info.delete.confirm',
  delete: 'operate.delete',
  cancel: 'operate.cancel',
  save: 'operate.save',
  update: 'operate.update',
  unsynchronized: 'label.unsynchronized',
  synchronized: 'label.synchronized',
  individual: 'label.individual',
  application: 'label.application',
  deactivate: 'label.deactivate',
  enable: 'label.enable',
  disable: 'label.disable',
  checkDataInfo: 'check.data.info',
  deleteTopicDomains: 'info.delete.topic.domains',
  clear: 'operate.clear',
  clearTopicDomainsRelationship: 'info.clear.topic.domains.relationship',
  withoutApprover: 'info.without.approver',
  commonDelete: 'info.common.delete',
  levelExists: 'info.level.exists',
  fillLevelApprover: 'info.fill.level.approver',
  toBeReleased: 'label.to.be.released',
  haveReleased: 'label.released',
  beOffline: 'label.be.offline',
  apiMode1: 'label.table.bootstrap.mode',
  apiMode2: 'label.script.mode',
  apiMode3: 'label.sql.mode',
  apiMode4: 'label.json.mode',
  selectUser: 'info.please.select.user',
  selectTree: 'info.please.select.tree',
  revocation: 'operate.revocation',
  operateDeactivate: 'operate.deactivate',

  unsync: "info.unsync",
  underReview: "info.under.review",
  approved: "info.approved",
  rejected: "info.rejected",
  finished: "info.finished",
  abandon: "info.abandon",
  withdrawn: "info.withdrawn",
  becameInvalid: "info.became.invalid",
  cancelled: "info.cancelled",
  all: "label.all",
  fillComment: "info.fill.comment",
  executionSuccess: "info.execution.success",
  executionFail: "info.execution.fail",
  checkingWait: "info.checking.wait",
  uploadAttachment: "info.checking.attachment",
  MasterData: "MasterData",
  ReferenceData: "ReferenceData",
  BusinessRecordData: "ReferenceData",
  IndicatorData: "IndicatorData",
  OperatePreview:"operate.data.preview",
  OperateView:"operate.view",
  OperateViewApi:"operate.view.api",
  OperateFeedback:"operate.feedback",
  askPermissionTip:"info.ask.permission.tip",
  selectCategory:"info.select.category",
  statusNew:"info.status.new",
  imageLimit20mb:"info.image.limit.20mb",
  dataNoPublish:"info.data.no.publish",
  previewPermissions:"info.preview.permissions",
  datePicValid:"info.date.pic.valid",
  dataTopicSelectCategory:"info.data.topic.select.category",
  unReviewable:"info.data.un.reviewable"
});
