import { OnInit, ChangeDetectorRef, EventEmitter } from '@angular/core';
import { Location } from '@angular/common';
import { Router, ActivatedRoute } from '@angular/router';
import { TranslateService } from '@ngx-translate/core';
import { AppMenuService } from '../../service/app-menu/app-menu.service';
import { HttpService } from '../../service/api/api.service';
import * as i0 from "@angular/core";
export declare class LayoutComponent implements OnInit {
    translate: TranslateService;
    router: Router;
    route: ActivatedRoute;
    private ref;
    private appMenuService;
    private http;
    private location;
    menuTreeKeys: any;
    menuTree: any;
    editUser: EventEmitter<string>;
    userDisplay: boolean;
    formData: any;
    logoffObj: any;
    layoutLogo: string;
    layoutLogoCollapsed: string;
    user: string;
    sidebarIcon: string;
    fullscreenExpand: string;
    fullscreenShrink: string;
    currentLanguage: any;
    langDesc: string;
    tabMenu: Array<any>;
    tabs: Array<any>;
    currentRegion: any;
    countries: Array<any>;
    selectedIndex: number;
    isCollapsed: boolean;
    fullPage: boolean;
    canGetData: boolean;
    hasScroll: boolean;
    isFullScreen: boolean;
    menuList: Array<any>;
    language: any;
    currRouter: any;
    username: string;
    currTabObj: any;
    contextMenuTab: any;
    contextMenuIndex: number;
    firstJoin: boolean;
    showContextMenu: boolean;
    items: any;
    constructor(translate: TranslateService, router: Router, route: ActivatedRoute, ref: ChangeDetectorRef, appMenuService: AppMenuService, http: HttpService, location: Location);
    private setCommand;
    ngOnInit(): Promise<void>;
    getItemByPath(menu: Array<any>, path: string): void;
    getTabObjByPath(path: string, list: Array<any>): null | undefined;
    buildSelectedIndex(): void;
    tempInit(): void;
    private setTab;
    initChangeLang(key: string): void;
    closeTab(index: number): void;
    chooseTab(index: number): void;
    tabClick(item: any, noNavigate?: boolean): void;
    isTabOpen(routerLink: string, tabName: string): boolean;
    logoff(): void;
    fullScreen(): void;
    exitFullScreen(): void;
    editUserEvent(): void;
    broadcastIframeUpdate(): void;
    initTabScroll(): void;
    scroll(type: string): void;
    closeAllTab(e: any): Promise<void>;
    closeOtherTab(e: any): Promise<void>;
    contextMenu(tab: any, index: number): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<LayoutComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<LayoutComponent, "app-layout", never, { "menuTreeKeys": "menuTreeKeys"; "menuTree": "menuTree"; }, { "editUser": "editUser"; }, never, never, false>;
}
